### ISSUE TITLE
Method 'Fusillade.RateLimitedHttpMessageHandler..ctor' not found.

### ISSUE THREAD

**Issue by brianmatic** [reactiveui/Fusillade#29]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Fusillade . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I upgraded our nuget package and I am getting this error.  Any ideas?

private T Background
		{
			get
			{
				return new Lazy<T>(() => createClient(
					new RateLimitedHttpMessageHandler(new NativeMessageHandler(), Priority.Background))).Value;
			}
		}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Fusillade, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Fusillade/package/nuget/Fusillade) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by giusepe** [comment]
Hi @brianmatic! 

Does it still happen with the current version of Fusillade?

**Comment by giusepe** [comment]
Considering that nothing else was mentioned in the last years and I have tested similar code with no problem, I'm closing this. 
If you do have any other questions related or not to this, please don't hesitate to ask.
