### ISSUE TITLE
What do the priorities mean?

### ISSUE THREAD

**Issue by adamfisher** [reactiveui/Fusillade#31]
I see the following priorities defined in the library but not all of them are spelled out in the read me. Could someone please shed some light on what each means and when to use them? Explicit is never mentioned at all.

```csharp
public enum Priority
  {
    Explicit = 0,
    Speculative = 10,
    Background = 20,
    UserInitiated = 100,
  }
```

**Comment by giusepe** [comment]
Hi @adamfisher, 

The precedence here is UserInitiated > Background > Speculative
Which means that anything set as UserInitiate has a higher priority than Background or Speculative. 

Explicit is the exception, it allows you to set an explicit value that can be higher, lower or in between any of these predefined cases. 

```csharp
var lowerThanSpeculative = new RateLimitedHttpMessageHandler(
                new HttpClientHandler(), 
                Priority.Explicit, 
                9);

var moreThanSpeculativeButLessThanBAckground = new RateLimitedHttpMessageHandler(
                new HttpClientHandler(), 
                Priority.Explicit, 
                15);

var doItBeforeEverythingElse = new RateLimitedHttpMessageHandler(
                new HttpClientHandler(), 
                Priority.Explicit, 
                1000);
```

**Comment by giusepe** [comment]
I have updated the README to explain this better, please let me know if you still need more information.
