### ISSUE TITLE
How to use Fusillade without ModernHttpClient in Xamarin Forms?

### ISSUE THREAD

**Issue by noelfernandes** [reactiveui/Fusillade#36]
Hi!
Considering that Stackoverflow does not have a tag for Fusillade, I'm not sure if I would get an answer there. I hope this is the right forum for this question, if not please excuse.

As per [this article](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/transport-layer-security), I would deduce that the use of ModernHttpClient within a XF project would be redundant. Would you be able to guide me on how I could use Fusillade (with Refit) without ModernHttpClient?

Thanks in advance.

**Comment by albilaga** [comment]
You can directly using `NetCache.Priority` for that

**Comment by giusepe** [comment]
@noelfernandes This is how I usually do: https://github.com/reactiveui/ReactiveUI/blob/update-cinephile/samples/xamarin-forms/Cinephile/Cinephile.Core/Rest/ApiService.cs
Hope it helps.
